version: '3'

services:
  apache:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: apache_${APP_ENV}
    ports:
      - '80:80'
    volumes:
      - ./php/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ../../../laravel:/var/www
    # Đợi cho mysql khởi động đã mới khởi động apache
    depends_on:
      - mysql

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: mysql
    environment:
      MYSQL_DATABASE: laravel_apache_${APP_ENV}
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/sql:/docker-entrypoint-initdb.d
    ports:
      - '23306:3306'