# Sử dụng ảnh mysql 8.0 của Docker Hub
FROM mysql:8.0

# Định nghĩa lệnh mặc định sẽ chạy khi container khởi chạy
# mysqld là lệnh khởi động Mysql server
CMD ["mysqld"]

# Chỉ định container lắng nghe trên port 3306
# Lệnh này không mở cổng mà chỉ lắng nghe trên cổng này khi được khởi chạy
EXPOSE 3306